zones:
  cam_01_zones:
    polygons:
    - id: zone_restricted_north
      name: Restricted Northern Perimeter
      enabled: true
      points:
      - - 0.0
        - 0.0
      - - 1.0
        - 0.0
      - - 1.0
        - 0.35
      - - 0.0
        - 0.35
      triggers:
        on_enter: true
        on_exit: false
        dwell_seconds: 5
        classes:
        - person
        - motorcycle
        - car
        - truck
      severity: HIGH
    - id: zone_vehicle_bay
      name: Vehicle Inspection Bay
      enabled: true
      points:
      - - 0.4
        - 0.6
      - - 0.9
        - 0.6
      - - 0.9
        - 1.0
      - - 0.4
        - 1.0
      triggers:
        on_enter: true
        on_exit: true
        dwell_seconds: 120
        classes:
        - car
        - truck
        - bus
        - motorcycle
      severity: MEDIUM
    tripwires:
    - id: wire_border_line
      name: Border Line
      enabled: true
      start:
      - 0.0
      - 0.5
      end:
      - 1.0
      - 0.5
      direction: both
      classes:
      - person
      - motorcycle
      - car
      - truck
      severity: CRITICAL
    - id: wire_exit_gate
      name: Exit Gate
      enabled: true
      start:
      - 0.6
      - 0.0
      end:
      - 0.6
      - 0.5
      direction: east_to_west
      classes:
      - car
      - truck
      severity: HIGH
  cam_usb_0_zones:
    polygons:
    - id: restricted_left
      name: Restricted Left Sector
      enabled: true
      points:
      - - 0.014100184467152894
        - 0.11541665395100911
      - - 0.25807049986603975
        - 0.11541665395100911
      - - 0.25807049986603975
        - 0.9404166539510092
      - - 0.014100184467152894
        - 0.9404166539510092
      triggers:
        on_enter: true
        dwell_seconds: 3.0
        classes:
        - person
      severity: HIGH
    tripwires:
    - id: tripwire_center
      name: Perimeter Center Line
      enabled: true
      start:
      - 0.55
      - 0.1
      end:
      - 0.55
      - 0.9
      direction: both
      classes:
      - person
      severity: CRITICAL
